### PR TITLE
Wider register initialization coverage for broader physical machine compatibility

### PR DESCRIPTION
**Pull request by woodrush**
This pull request allows initialization of `%dx` at the beginning right after booting for a more wider coverage of initialized registers, without changing the program size. I've tested that while the prior commit (the `HEAD` at `main`) did not run on my own machine (the interpreter crashed), this PR allows SectorLISP to actually run on my own machine using USB booting. It has a small additional effect of a newline being printed only once right after booting. Considering the effect that this pull request makes, I believe that this should allow SectorLISP to run successfully on a more broader set of machines.

This is done by moving `call PutChar` and `mov $'\r',%al` to the beginning of `main` as follows:
```asm
main:	mov	%sp,%cx
	mov	$'\r',%al
	call	PutChar
	call	GetToken
```
This ultimately initializes `%dx`, since `PutChar` writes to `%ah` and `%al`, then finally does `xchg %dx,%ax`. Before this commit, `%dx` was not initialized after booting, causing the program to not run properly on some machines.

The machine I used for testing is an Acer Aspire One with an Intel Atom N270 CPU. I was able to successfully run [bootBASIC](https://github.com/nanochess/bootBASIC) and [retro2048](https://github.com/CrociDB/retro2048) on this machine, but could not run the current SectorLISP (the `HEAD` of `main`) on it, where the interpreter crashed right after I typed `(` as the first character. After this commit, I was able to run SectorLISP on the same machine successfully, where I tested all of the builtin forms.

I tested all of the expressions in `test1.lisp`, as well as the following ones:

```lisp
((LAMBDA (X) (X))
 (QUOTE (LAMBDA () (CONS (QUOTE (1 2)) (CONS (QUOTE 3) NIL)))))

(COND ((ATOM (QUOTE (1 2))) (QUOTE A))
      ((QUOTE T) (QUOTE B)))

(CAR (QUOTE (1 2 3)))
(CDR (QUOTE (1 2 3)))

((LAMBDA (X) (CONS X X)) (QUOTE (1 2)))
;;=> ((1 2) 1 2)

(CONS (QUOTE (1 2)) (QUOTE (3 4)))
;;=> ((1 2) 3 4)
```

I also tested this pull request on Blinkenlights and QEMU with all of the tests included in `./test`, and confirmed that they all run successfully.

This pull request has a small additional effect where one newline is printed right after booting, since `PutChar` is moved to the beginning. From then on, the behavior does not change. I feel that the initial newline serves as an indication that the system is ready to take inputs. On my machine, there is a little bit of time before the cursor prints the newline, so for me it was nice to know when I could start writing the inputs.

Although the physical machines that I have tested this on is only my own machine, since the effect of the PR is that it makes the range of initialized registers more broader, I think that this does not narrow the set of runnable machines or just alters them, but will broaden the set of runnable machines.

### CODE REVIEW

**Comment by woodrush** [comment]
I found this fix by comparing the last commit that worked on my machine with the next one which doesn't. The last working commit was 5a33a6b97a where GC was added, and the next commit didn't work.

Analyzing parts of the diff, It turned out that the following lines were critical:

https://github.com/jart/sectorlisp/commit/d587ce19d1118555adb34322a70b46ca5a2f3223#diff-2dbbb823dfbbcfe8f7cd18827970a5c15f89fe8ada12dc48ab37991d5974b4bfL69-R71

Leaving out only this change and applying everything else in this commit in fact made a version that would run on my machine.

I then took a leap and tried putting `mov $'\n',%dl` at the beginning of `main` in the latest commit, and found out that this one change in fact makes the code run on my machine.

Since the critical instruction here is `mov $'\n',%dl`, I was looking for a way to initialize `%dl` at the beginning without adding any bytes, and came up with this solution.

**Comment by woodrush** [comment]
I added a comment saying `# Call first to initialize %dx` for clarity.

**Comment by jart** [comment]
This is a good change. I like how you achieved a net zero size impact in a way that actually makes the UI better.

**Review by jart — APPROVED** [review]

**Comment by woodrush** [comment]
Thanks!

**Pull request merged**
