### PR TITLE
shave some bytes

### PR DESCRIPTION
**Pull request by peterferrie**

### CODE REVIEW

**Comment by jart** [comment]
OK so before you showed up, SectorLISP looked like this:

image

Then you sent us #9 and SectorLISP became this:

image

Now with your latest contribution here, SectorLISP becomes this:

image

That's pretty cool. At this point we've outpaced SectorFORTH and we might even have the option of adding garbage collection. However I'm noticing a regression:

image

Have you tried running the qemu regression tests @agreppin wrote in the test folder? Side note: I haven't managed to get them to work with the qemu that's on my alpine and debian systems. Qemu is so hard to automate which is one of the reasons why I wrote Blinkenlights but it's also very new so there could be a bug in that.

**Comment by peterferrie** [comment]
There is a regression in some of the tests.  I will fix it.

**Comment by peterferrie** [comment]
eval10 passes now.  Test1 was passing already, which hid the problem.  I will try eval15 tomorrow but my system is very slow, otherwise I would know already.

**Comment by peterferrie** [comment]
line 179 (je .retF) is currently long (four bytes).  It might be possible to rearrange the code so that it is short, to save another two bytes, but I did not succeed.

**Comment by agreppin** [comment]
For testing I prefer to use the BOCHS emulator (GUI) which has a copy-paste feature which is way faster than using the  `quemu.sh` test script.

**Comment by peterferrie** [comment]
eval15 passes, too.  I believe that the updated PR is stable now.
I've been using two VirtualBox VMs running Debug under DOS, allowing me to perform side-by-side comparison of memory, and to single-step through the code.  Of course, it requires that I type each line twice, *carefully* because of no back-space support. :-)  However, it has save-states so if I make a mistake I can revert.  it works well enough.

**Comment by peterferrie** [comment]
If a higher segment value is chosen (e.g. 0x80) and the buffer at 0x4080 is moved to 0x0000 (and the buffer at 0x4000 goes somewhere else like 0x8000), then another four bytes can be saved.

**Review by jart — APPROVED** [review]
Confirmed. Looks good to me. Thank you for your contribution!

image

**Comment by jart** [comment]
For the record, we're now at 475 bytes!

**Comment by peterferrie** [comment]
> For the record, we're now at 475 bytes!

~6% reduction.  That's cool.  I'm out of ideas for now.
Thanks.

**Comment by jart** [comment]
Indeed. In the interest of recognizing your efforts, I've sent you an invite for collaborator status. You're welcome to make yourself at home and put your name (or your employers name) at the top of the file if you want it.

@peterferrie @agreppin Since we're now requiring CMOV, is there any reason we can't use %bp? If so we can shave off six more bytes. https://github.com/jart/sectorlisp/commit/9bb9c6e04c9c727cd3f84755a65f269012235c5d

**Comment by jart** [comment]
We also might be able to do another 15 bytes if we change the memory model and treat the program itself as an interned string. Haven't got it working yet.

image

**Comment by peterferrie** [comment]
> Indeed. In the interest of recognizing your efforts, I've sent you an invite
> for collaborator status. You're welcome to make yourself at home and put
> your name (or your employers name) at the top of the file if you want it.

Thanks.  If I can contribute further then I will add my name.
I don't want to add it as its own revision.

> @peterferrie @agreppin Since we're now requiring CMOV, is there any reason
> we can't use %bp? If so we can shave off six more bytes.

Yes!  %bp becomes safe to use since no recent BIOS has the scroll bug.
Alternatively, I can work to remove the use of CMOV. :-)

**Comment by jart** [comment]
It's worth doing if we find someone who can make a YouTube video of it running on the original hardware.

**Comment by peterferrie** [comment]
If we replace fs with bp (but lose the ONE optimisations), and if I
can avoid the cmov, we'd have 8088 compatibility.  I will work on the
cmov part, if you will consider the bp part. :-)

**Comment by peterferrie** [comment]
Or maybe two versions - 8088 and 686+.  It looks like the cmov fix
requires adding one more byte.

**Comment by jart** [comment]
I found someone on Twitter who might be able to help. https://twitter.com/MobyGamer/status/1457580487866822658

**Comment by peterferrie** [comment]
Jim is great.  We have known each other for a long time.

**Pull request merged**
