### PR TITLE
smaller Intern function

### PR DESCRIPTION
**Pull request by ilyakurdyukov**
Created a PR as you requested.

### CODE REVIEW

**Comment by agreppin** [comment]
This can't be merged as is because of the bug spotted in issue https://github.com/jart/sectorlisp/issues/5#issuecomment-860163502  This can be fixed easily but the author seems to have dropped his sectorlisp fork... 

And the change in start.S was never discussed anywhere in https://github.com/jart/sectorlisp/issues/5.

**Comment by jart** [comment]
Not dropped. Just put on the backburner. Let's bump this up on the list of priorities.

**Review by jart — APPROVED** [review]
LGTM. Thank you for your contribution @ilyakurdyukov. Sorry about the delay!

**Comment by ilyakurdyukov** [comment]
Please fix this introduced bug after this pull:
https://github.com/jart/sectorlisp/issues/5#issuecomment-860163502 (PutChar shouldn't be moved. Or you need to uncomment "jmp PutChar" on the old PutChar location.)

**Comment by jart** [comment]
@agreppin has an exciting branch that's based off this PR so it'll be fixed shortly. https://github.com/agreppin/sectorlisp/commit/58b5b9e73b12ae72519b5bae708f137689bc686d

**Pull request merged**
