### PR TITLE
Fix lambda variable referencing bug in QEMU

### LINKED ISSUE #18: Referencing bound variables in lambdas crashes the interpreter in QEMU
Evaluating the following expression in QEMU using `make test1` crashes the interpreter:
```
((LAMBDA (B) B)(QUOTE C))
```
When this expression starts being evaluated, the interpreter stops running and no output or input prompts occur afterwards.

The following expressions do work:
```
((LAMBDA () (QUOTE A)))
((LAMBDA (B) (QUOTE A))(QUOTE C))
```
The difference here is whether the bounded variables are referenced or not, so it seems that referencing bounded variables in lambdas are currently failing.

Since variable bindings do not work, the metacircular evaluator in `./test/eval10.lisp` and `eval15.lisp` doesn't work as well.

This issue does not happen at all in Blinkenlights, so it may be an x86 forward compatibility issue.

### PR DESCRIPTION
**Pull request by woodrush**
Fixes #18, where referencing variables inside lambdas crashed the interpreter in QEMU.

This pull request replaces `.byte 0xF6` at `Assoc:` with `.byte 0xA9`, which:

- Works on Blinkenlights as well
- Does not add any bytes to the program
- Was found by an exhausitve search over all of the possible bytes
- Only consists of `cmp` and `test`, where both of them only has effects on the flags
  - The instructions after this byte become the following, found using Blinkenlights:
    ```asm
    a98b39      test    $_edata+0x298b,%ax
    3caf        cmp     $-0x51,%al
    8b05        mov     (%di),%ax          # The instruction at `Car:` which we want for it to run
    ```
- Is able to run the program [meta-in-meta.lisp](https://github.com/woodrush/sectorlisp/blob/add-meta-in-meta/test/meta-in-meta.lisp), which is a metacircular evaluator nested in a metacircular evaluator, on both QEMU and Blinkenlights
  - Before this pull request, since variable bindings in lambdas did not work, many examples including the original metacircular evaluator did not work on QEMU

I'll share the details of how this solution was found in the replies.

(Edit: link to meta-in-meta.lisp)

### CODE REVIEW

**Comment by woodrush** [comment]
Upon finding this solution, I first did an exhaustive search over all of the possible bytes by using the QEMU tests in `./test`, and got the following table of usable bytes:

```
Lambda  eval10  eval15  meta-in-meta
------------------------------------
0x05    0x05    0x05    0x05
0x0D    0x0D    0x0D    0x0D
0x15    0x15    0x15    0x15
0x1D    0x1D    0x1D    0x1D
0x25    0x25    0x25    0x25
0x2D    0x2D    0x2D    0x2D
0x35    0x35    0x35    0x35
0x3D    0x3D    0x3D    0x3D
0x6B    
0x80    0x80    0x80    0x80
0x82    0x82    0x82    0x82
0x83    0x83    0x83    0x83
0xA0    0xA0    0xA0    0xA0
0xA1    0xA1    0xA1    0xA1
0xA2    0xA2    0xA2    0xA2
0xA3    0xA3    0xA3    0xA3
0xA9    0xA9    0xA9    0xA9
0xB8    0xB8    0xB8    0xB8
0xB9     
0xBA     
0xBB     
0xBD    0xBD    0xBD    0xBD
0xBE    0xBE    0xBE    0xBE
0xC0    0xC0    0xC0    0xC0
0xC1    0xC1    0xC1    0xC1
0xC6    0xC6    0xC6    0xC6
```

- `Lambda` is `((LAMBDA (B) B)(QUOTE C))`. A similar expression can be found in `test1.lisp` by running `make test1`.
- `eval10` and `eval15` are the metacircular evaluators included in `./test`, testable via `make eval10` and `make eval15`.
- `meta-in-meta` is [meta-in-meta.lisp](https://github.com/woodrush/sectorlisp/blob/add-meta-in-meta/test/meta-in-meta.lisp), a nested version of the metacircular evaluator, where I directly nested `eval15.lisp` into the meta-expression of `eval15.lisp` itself. (It was very cool that this program works as well!) It is accessible via `make meta-in-meta`. I believe that `meta-in-meta` is powerful enough to serve as a good test.
  - I also tried running a `meta-in-meta-in-meta` program with 3 layers, but this didn't run on Blinkenlights and the JavaScript version available at https://justine.lol/sectorlisp2/ , so I believe it uses too much memory.

I also confirmed that all of the values in the table are valid in Blinkenlights as well, by running `meta-in-meta` using these byte changes.

Since each row in this table has a progressively sophisticated program, I only ran the bytes that were valid for the previous row, except for `Lambda` which I ran it on all 256 values.

Here is a list of the instruction interpretations at the inserted byte:

```
Working
Byte    Instruction 1                           Instruction 2
-------------------------------------------------------------------------------
0x05    058b39      add     $_edata+0x298b,%ax; 3caf        cmp     $-0x51,%al
0x0D    0d8b39      or      $_edata+0x298b,%ax; 3caf        cmp     $-0x51,%al
0x15    158b39      adc     $_edata+0x298b,%ax; 3caf        cmp     $-0x51,%al
0x1D    1d8b39      sbb     $_edata+0x298b,%ax; 3caf        cmp     $-0x51,%al
0x25    258b39      and     $_edata+0x298b,%ax; 3caf        cmp     $-0x51,%al
0x2D    2d8b39      sub     $_edata+0x298b,%ax; 3caf        cmp     $-0x51,%al
0x35    358b39      xor     $_edata+0x298b,%ax; 3caf        cmp     $-0x51,%al
0x3D    3d8b39      cmp     $_edata+0x298b,%ax; 3caf        cmp     $-0x51,%al
0x80    808b393caf  orw     $-0x51,_edata+0x2c
0x82    828b393caf  orw     $-0x51,_edata+0x2c
0x83    838b393caf  orw     $-0x51,_edata+0x2c
0xA0    a08b39      mov     _edata+0x298b,%al ; 3caf        cmp     $-0x51,%al
0xA1    a18b39      mov     _edata+0x298b,%ax ; 3caf        cmp     $-0x51,%al
0xA2    a28b39      mov     %al,_edata+0x298b ; 3caf        cmp     $-0x51,%al
0xA3    a38b39      mov     %ax,_edata+0x298b ; 3caf        cmp     $-0x51,%al
0xA9    a98b39      test    $_edata+0x298b,%ax; 3caf        cmp     $-0x51,%al
0xB8    b88b39      mov     $_edata+0x298b,%ax; 3caf        cmp     $-0x51,%al
0xBD    bd8b39      mov     $_edata+0x298b,%bp
0xBE    be8b39      mov     $_edata+0x298b,%si
0xC0    c08b393caf  ror     $0xaf,_edata+0x2c3
0xC1    c18b393caf  ror     $0xaf,_edata+0x2c3
0xC6    c68b393caf  movw    $0xaf,_edata+0x2c3

Non-working
Byte    Instruction 1                           Instruction 2
-------------------------------------------------------------------------------
0x6B    6b8b393caf  imul    $-0x51,_edata+0x2c  
0xB9    b98b39      mov     $_edata+0x298b,%cx; 3caf        cmp     $-0x51,%al
0xBA    ba8b39      mov     $_edata+0x298b,%dx; 3caf        cmp     $-0x51,%al
0xBB    bb8b39      mov     $_edata+0x298b,%bx; 3caf        cmp     $-0x51,%al
```

I used Blinkenlights to obtain this table.

Among these instructions, I think `0x3D` and `0xA9` have the least impact to the environment and is the safest to use, since it only consists of `cmp` and `test`, where both of them only has effects on the flags, and the results are not stored anywhere.
I personally like `0xA9` since it represents the Load Accumulator instruction on the MOS 6502.

(Edit: link to meta-in-meta.lisp)

**Comment by woodrush** [comment]
I decided to leave out [meta-in-meta.lisp](https://github.com/woodrush/sectorlisp/blob/add-meta-in-meta/test/meta-in-meta.lisp) from this pull request to keep the codebase simple, and since `eval10.lisp` and `eval15.lisp` already serves as a good enough test for the purpose of this PR, according to the byte testing table I mentioned above. I'll be happy to send a separate pull request if it seems fitting for this repo.

**Comment by peterferrie** [comment]
How does this fix the issue?  Now we run two instructions instead of one, but the result is the same - only flags altered.

**Comment by woodrush** [comment]
I'm new to x86 assembly, but based on what I researched, I believe it's some kind of a compatibility issue or possibly a Blinkenlights issue.

According to a disassembler at [https://gchq.github.io/CyberChef/...](https://gchq.github.io/CyberChef/#recipe=Disassemble_x86('16','Full%20x86%20architecture',16,0,true,true)&input=ZjY4YiAzOTNjIGFmOGIgMDVjMw), I get the following result for the disassembly starting at `0xF6` (the byte used now), where `0xF6` is read as an unknown instruction:
```
0016:0000 F6                              ???
0016:0001 8B39                            MOV DI,WORD PTR [BX+DI]
0016:0003 3CAF                            CMP AL,AF
0016:0005 8B05                            MOV AX,WORD PTR [DI]
0016:0007 C3                              RET
```
Whereas if I replace it with `0xA9`, I get the intended result:
```
0016:0000 A98B39                          TEST AX,398B
0016:0003 3CAF                            CMP AL,AF
0016:0005 8B05                            MOV AX,WORD PTR [DI]
0016:0007 C3                              RET
```
I tried putting the entire 436 bytes of assembly into the disassembler as well and got similar results near the byte in question. The disassembler also seems to be correctly disassembling the entire program as well.

Another disassembler at https://onlinedisassembler.com/odaweb/ provides similar results.

An x86 reference page http://ref.x86asm.net/ says that `0xF6` (the byte being used now) is an example of an extended opcode, where the bits in the next byte determine the instruction. On http://ref.x86asm.net/coder32.html#xF6 it says that `0xF6` could either be `test` (which is intended), `not`, `neg`, `mul`, `imul`, `div` or `idiv`. I tried changing the next byte on the disassembler and for some bytes `0xF6` indeed did got read as a valid instruction.

Since the QEMU VM used in the test is `qemu-system-x86_64`, one of my guesses is that it is a compatibility issue with QEMU and i8086. However, since the second disassembler (https://onlinedisassembler.com/odaweb/) is able to specifically specify i8086 among over about 100 architectures, I believe `F6 8B 39 3C AF` is an unknown instruction in i8086. I'm not sure if the fact that the code is run on the boot sector affects the interpretation of the machine code.

The version for QEMU I'm using is the following:
```
$ qemu-system-x86_64 --version
QEMU emulator version 4.2.1 (Debian 1:4.2-3ubuntu6.18)
```

Blinkenlights, on the other hand, interprets `F6 8B 39 3C AF` as `f68b393caf  testw   $-0x51,_edata+0x2c39(%bp,%di)`. How does Blinkenlights get this interpretation? Why is this different from the other disassemblers? Is it a feature specific for boot sectors?

Based on these results, my best explanation at this point for why replacing the byte solves this issue is that somehow the behavior of QEMU and Blinkenlights is different, but I'm not sure why the behavior is different.

**Comment by peterferrie** [comment]
> I'm new to x86 assembly, but based on what I researched, I believe it's some
> kind of a compatibility issue or possibly a Blinkenlights issue.
>
> According to a disassembler at
> [https://gchq.github.io/CyberChef/...](https://gchq.github.io/CyberChef/#recipe=Disassemble_x86('16','Full%20x86%20architecture',16,0,true,true)&input=ZjY4YiAzOTNjIGFmOGIgMDVjMw),
> I get the following result for the disassembly starting at `0xF6` (the byte
> used now), where `0xF6` is read as an unknown instruction:
> ```
> 0016:0000 F6                              ???
> 0016:0001 8B39                            MOV DI,WORD PTR [BX+DI]

Okay, F6 88+n is an alias for F6 80+n, and should be displayed as (in
Intel format):

F6 8B xx xx yy  TEST  BYTE PTR SS:[BP+DI+xxxx],yy

> Whereas if I replace it with `0xA9`, I get the intended result:
> ```
> 0016:0000 A98B39                          TEST AX,398B
> 0016:0003 3CAF                            CMP AL,AF

Fair enough.  A real CPU (even a modern one) will execute the original
instruction, even if an emulator doesn't.

> Another disassembler at https://onlinedisassembler.com/odaweb/ provides
> similar results.

IDA displays the correct result.

> Blinkenlights, on the other hand, interprets `F6 8B 39 3C AF` as `f68b393caf
>  testw   $-0x51,_edata+0x2c39(%bp,%di)`. How does Blinkenlights get this
> interpretation? Why is this different from the other disassemblers? Is it a
> feature specific for boot sectors?

No, it's due to a different source of documentation.

> Based on these results, my best explanation at this point for why replacing
> the byte solves this issue is that somehow the behavior of QEMU and
> Blinkenlights is different, but I'm not sure why the behavior is different.

Okay, I'm happy with this change.

**Comment by jart** [comment]
I'm happy with this change too. If we can support more emulators without sacrificing bytes then it's a no brainer. This was pointed out earlier, but the best explanation I've found so far is from the x86ref website, which has a footnote for instructions with the octal prefix `0366 0?1?`:

```
   20. TEST
         1. sandpile.org -- IA-32 architecture -- opcode groups
         2. Christian Ludloff wrote: While the latest Intel manuals still omit this de-facto standard, the recent x86-64 manuals from AMD document it.
         3. AMD64 Architecture Programmer's Manual Volume 3, Table One-Byte and Two-Byte Opcode ModRM Extensions
```

The disassembler that Intel uses is called Xed and Blinkenlights actually embeds it to do the instruction decoding. 

```
xed -isa-set -r -chip-check ALL -as 0x166 -i sectorlisp.o | less
XDIS 166: LOGICAL   BASE       I86        F68B393CAF               test byte ptr [bp+di*1+0x3c39], 0xaf
# Total Errors: 0
# Total Chip Check Errors: 0
```

Nice LISP program @ https://github.com/woodrush/sectorlisp/blob/add-meta-in-meta/test/meta-in-meta.lisp BTW.

**Comment by woodrush** [comment]
Thanks @peterferrie and @jart for the analysis. It was new knowledge for me that some emulators and disassemblers have different behaviors. I also installed Xed from https://github.com/intelxed/xed and got the same results for the `F68B393CAF` part. I'll be using Xed when I need some disassembling, thanks for the info.

Also thanks @jart for your compliment! It was cool that SectorLISP can run this successfully.

I wanted to say that I was very inspired by this project, and It's exciting diving into it and seeing how it works. I always wanted to do some extensive assembly programming, and I'm having a lot of fun exploring this project.

**Pull request merged**
